services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./spot_model.json:/app/model.json:ro
      - ./analysis.csv:/app/analysis.csv:rw
      - ./.secrets.toml:/e4efs/config/.secrets.toml:ro
      - ./settings.toml:/e4efs/config/settings.toml:ro
    deploy:
      resources:
        limits:
          cpus: 32
          memory: 8G
    user: "${USER_ID}:${GROUP_ID}"
