[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fishsense_gmm_laser_detector"
version = "0.1.0"
description = "Fishsense GMM Laser Detector"
authors = [
    "UCSD Engineers for Exploration <e4e@ucsd.edu>"
]
license = "UCSD"
readme = "README.md"
repository = 'https://github.com/UCSD-E4E/fishsense-2025-04-16-laser-detect-analysis'

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.5"
matplotlib = "^3.10.1"
scikit-learn = "^1.6.1"
rawpy = "^0.24.0"
# pyfishsensedev = {git = "https://github.com/UCSD-E4E/pyFishSenseDev.git", rev = "9d6c016a23c34616ebf759d648401a147571e80b"}
opencv-python-headless = "^4.11.0.86"


[tool.poetry.group.dev.dependencies]
pylint = "^3.2.7"
pytest = "^8.3.2"
jupyter = "^1.1.1"
autopep8 = "^2.3.1"
coverage = "^7.6.1"
pandas = "^2.2.3"



[tool.poetry.group.analyze.dependencies]
requests = "^2.32.3"
matplotlib = "^3.10.1"
dynaconf = "^3.2.10"

[tool.semantic_release]
version_variables = ["fishsense_gmm_laser_detector/__init__.py:__version__"]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main)"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true